version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    restart: 'unless-stopped'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: -p 5432
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pg:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ./
      args: $PORT
    restart: always
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      
volumes:
  pg:

