export enum ValidationEnum {
  notString = 'Должно быть строкой',
  notInt = 'Должно быть целым числом',
  notUUID = 'Не соответствует типу UUID',
  notEmail = 'Введён некорректный почтовый адрес',
  incorrectPhoneNumber = 'Введён некорректный номер телефона',
  notArray = 'Должно быть массивом',
  notJWT = 'Не является JWT',
  notFile = 'Не является файлом',
  nameNotEmpty = 'Название не должно быть пустым',
  notValueType = 'Не соответствует ожидаемому типу данных',
  notNumber = 'Должно быть числом',
  notRateType = 'Данного тарифа не существует',
  notBoolean = 'Должно быть булевым значением',
  notConfigType = 'Данного типа конфигурации не существует',
  notDecimal = 'Должно быть типом decimal',
  notInt32 = 'Должно быть типом int32',
  notValidStringSize = 'Строка не должна превышать длину в 80 символов',
  notTimeZone = 'Не является часовым поясом',
  notDateString = 'Не является датой',
}
